In [2]:
import numpy as np

a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

In [3]:
a.dot(b)

12.0

In [4]:
np.dot(a, b)

12.0

In [5]:
trans_a = a.reshape(1, 3)
np.dot(trans_a, b)
# 点乘得到的矩阵行数等于前者，列数等于后者
# The result of dot, 
# its number of row equals to the former matrix
# its number of column equals to the latter matrix

# a m*n matrix, 
# the number of row is m
# the number of column is n 

array([12.])

In [7]:
np.dot(b, trans_a)

ValueError: shapes (3,) and (1,3) not aligned: 3 (dim 0) != 1 (dim 0)

In [12]:
print(a.shape)
trans_a.shape

(3,)


(1, 3)

In [3]:
type(a)

numpy.ndarray

In [4]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)

In [5]:
c

array([[ -0.64307333,  16.57745647, -18.78374428, ...,  -5.20606813,
          6.08162296,   3.05085354],
       [-13.89227274,  18.69803755,  -6.88843028, ...,  14.92190686,
         -5.16992746,  13.81005321],
       [ 15.81244095, -16.55220883, -34.03648028, ...,   9.78042216,
         17.53297582,   7.22368373],
       ...,
       [-13.13715748,  16.24078077,  27.59680172, ...,  -9.07285502,
         -9.45210379,   0.7820476 ],
       [  2.30651933,  -7.02665513, -14.33415172, ...,  -5.07908901,
         14.85430667,   6.7975108 ],
       [ 19.75702811,   2.74268402,  16.68777681, ...,  -1.70642154,
         -5.94042743,   1.12069457]])

In [6]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [7]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

In [8]:
c

array([[-0.11180579, -0.70209405, -0.81263243],
       [ 0.03200941,  0.06871786, -0.03474849],
       [ 0.03619942, -0.00584399,  0.00164792]])